[package]
name = "intcode-lex"
version = "0.0.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
publish = false

[dependencies]
dairy = "0.2.2"
intcode-error = { path = "../error" }
